// resources/js/components/UI/MaterialInput.jsx
import { useState } from "react";


const MaterialInput = ({ type, label, error, handleChange }) => {

    const [isFocus, setFocus] = useState(false)
    console.log()

    return (
        <>
            <label className={`materil-group recovery__field ${error.hasError ? 'error' : ''} ${isFocus ? 'active' : ''}`}>
                <span className="materil-group__label">{label}</span>
                <input type={type}
                       className="form-control base-input materil-group__input"
                       onChange={(e) => {handleChange(e.target.value)}}
                       onFocus={() => {setFocus(true)}}
                       onBlur={(e) => { e.target.value == '' ? setFocus(false) : setFocus(true)}}
                />
            </label>
            {error.hasError ? <p className="xs text-danger error-message">{error.errorMessage}</p> : null}
        </>
    )
}

export default MaterialInput;

// resources/js/components/UI/MaterialInput.vue
<template>
        <label class="materil-group recovery__field" :class="{'active' : isFocus, 'error': error.hasError}">
            <span class="materil-group__label">{{label}}</span>
            <input :type="type" class="form-control base-input materil-group__input"
                   v-model="value"
                   @input="handleInput"
                   @focus="isFocus = true"
                   @blur="isFocus = value == '' ? false : true"
            >
        </label>
        <p v-if="error.hasError" class="xs text-danger" style="margin-top: -12px; transform: translateY(-8px)">{{ error.errorMessage }}</p>
</template>

<script>
import {ref} from 'vue'
export default {
    name: 'MaterialInput',
    props: ['type', 'label', 'error'],
    emits: ['handleChange'],
    setup(props, { emit }) {
        let isFocus = ref(false)
        let value = ref('');

        const handleInput = (e) => {
            emit('handleChange', e.target.value)
        }

        return {
            isFocus,
            value,
            handleInput,
        }
    }
}
</script>
