// Vue/components/UI/MaterialPhoneInput.vue
<template>
    <label class="materil-group recovery__field" :class="{'active' : isFocus, 'error': error.hasError}">
        <span class="materil-group__label">{{label}}</span>
        <input :type="type" class="form-control base-input materil-group__input phone-input"
               ref="phoneInput"
               v-model="value"
               @input="handleInput"
               @focus="isFocus = true"
               @blur="isFocus = value == '' ? false : true"
        >
    </label>
    <p v-if="error.hasError" class="xs text-danger" style="margin-top: -12px; transform: translateY(-8px)">{{ error.errorMessage }}</p>
</template>

<script>
import {ref, onMounted} from 'vue'
import Inputmask from 'inputmask';
export default {
    name: 'MaterialPhoneInput',
    props: ['type', 'label', 'error'],
    emits: ['handleChange'],
    setup(props, { emit }) {
        let isFocus = ref(false)
        let value = ref('');

        const phoneInput = ref(null);
        const handleInput = (e) => {
            emit('handleChange', e.target.value)
        }

        onMounted(() => {
            Inputmask({ "mask": "+7(999) 999-99-99" }).mask(phoneInput.value);
            console.log(value.value)
        })
        return {
            isFocus,
            value,
            phoneInput,
            handleInput,
        }
    }
}
</script>

// resources/js/components/UI/MaterialPhoneInput.jsx
import { useState, useEffect, useRef } from "react";
import Inputmask from 'inputmask';

const MaterialPhoneInput = ({ type, label, error, handleChange }) => {

    const [isFocus, setFocus] = useState(false)
    const phoneInput = useRef();

    useEffect(() => {
        Inputmask({ "mask": "+7(999) 999-99-99" }).mask(phoneInput.current);
    }, [])

    return (
        <>
            <label className={`materil-group recovery__field ${error.hasError ? 'error' : ''} ${isFocus ? 'active' : ''}`}>
                <span className="materil-group__label">{label}</span>
                <input
                    ref={phoneInput}
                    type={type}
                    className="form-control base-input materil-group__input"
                    onChange={(e) => {handleChange(e.target.value)}}
                    onFocus={() => {setFocus(true)}}
                    onBlur={(e) => { e.target.value == '' ? setFocus(false) : setFocus(true)}}
                />
            </label>
            {error.hasError ? <p className="xs text-danger error-message">{error.errorMessage}</p> : null}
        </>
    )
}

export default MaterialPhoneInput;
