// Vue/views/Login.vue
<template>
    <Header />
    <div class="content content--recovery">
        <div class="container">
            <div class="register">
                <h2 class="h2 recovery__title register__title">
                    Вход
                </h2>
                <div class="register-forms">
                    <form action="" id="form-individual" class="refister__form">
                        <MaterialInput type="text" label="Логин" @handleChange="setLogin" :error="errorLogin"/>
                        <MaterialInput type="password" label="Пароль" @handleChange="setPassword" :error="errorPassword"/>
                        <p v-if="errorCredentials" class="xs text-danger" style="margin-top: -12px; transform: translateY(-8px)">Не верный логин или пароль</p>
                        <button type="button" class="btn btn-primary btn-block" @click="sendForm">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <Footer />
</template>

<script>
    import {ref, onMounted} from "vue";
    import router from "../router/router";
    import Header from "../components/Header/Header.vue";
    import Footer from "../components/Footer/Footer.vue";
    import MaterialInput from "../components/UI/MaterialInput.vue";
    import api from "../api";

    export default {
        name: 'Home',
        components: {
            MaterialInput,
            Header,
            Footer
        },
        setup(props) {
            let login = ref('')
            let password = ref('')
            let errorLogin = ref({hasError: false, errorMessage: ''})
            let errorPassword = ref({hasError: false, errorMessage: ''})
            let errorCredentials = ref(false)

            const setLogin = (value) => {
                login.value = value
                errorLogin.value.hasError = false
            }

            const setPassword = (value) => {
                password.value = value
                errorPassword.value.hasError = false;
            }

            const sendForm = () => {
                if(login.value == '' || login.value.length < 3) {
                    errorLogin.value.hasError = true;
                    errorLogin.value.errorMessage = 'Введите логин'
                }


                if(password.value.length < 6) {
                    errorPassword.value.hasError = true;
                    errorPassword.value.errorMessage = 'Пароль должен содержать не менее 6 символов'
                }

                if(!errorLogin.value.hasError && !errorPassword.value.hasError) {
                    console.log('send')
                    api.post('/api/auth/login',{
                        login: login.value,
                        password: password.value,
                    }).then((res) => {
                        localStorage.setItem('access_token', res.data.access_token)
                        router.push('/')
                    }).catch((error) => {
                        console.log(error)
                        errorCredentials.value = true
                    })
                }
            }

            return {
                login,
                password,
                errorLogin,
                errorPassword,
                errorCredentials,
                setLogin,
                setPassword,
                sendForm,
            }
        }
    }
</script>

// resources/js/pages/Login.jsx
import { useState } from "react";
import { Navigate, useNavigate } from 'react-router-dom'

import api from "../api";
import Header from "../components/Header";
import MaterialInput from "../components/UI/MaterialInput";
import Footer from "../components/Footer";

const Login = () => {
    const navigate = useNavigate();
    const isAuth = !!localStorage.getItem('access_token')

    if(isAuth) {
        return <Navigate to={'/'} />
    }


    const [login, setLogin] = useState('');
    const [password, setPassword] = useState('');
    const [errorLogin, setErrorLogin] = useState({hasError: false, errorMessage: ''})
    const [errorPassword, setErrorPassword] = useState({hasError: false, errorMessage: ''})
    const [errorCredentials, setErrorCredentials] = useState(false)

    const handleLogin = (value) => {
        setLogin(value)
        setErrorLogin({hasError: false, errorMessage: ''})
    }

    const handlePassword = (value) => {
        setPassword(value)
        setErrorPassword({hasError: false, errorMessage: ''})
    }

    const sendForm = (e) => {
        e.preventDefault()

        if (login == '' || login.length < 3) {
            setErrorLogin({hasError: true, errorMessage: 'Введите логин'})
        }

        if (password.length < 6) {
            setErrorPassword({hasError: true, errorMessage: 'Пароль должен содержать не менее 6 символов'})
        }

        if(!errorLogin.hasError && !errorPassword.hasError) {
            console.log('send')
            api.post('/api/auth/login',{
                login: login,
                password: password,
            }).then((res) => {
                console.log(res)
                localStorage.setItem('access_token', res.data.access_token)
                navigate("/");
            }).catch((error) => {
                console.log(error)
                setErrorCredentials(true)
            })
        }
    }

    return (
        <>
            <Header/>
            <div className="content content--recovery">
                <div className="container">
                    <div className="register">
                        <h2 className="h2 recovery__title register__title">
                            Вход
                        </h2>
                        <div className="register-forms">
                            <form action="" id="form-individual" className="refister__form" onSubmit={(e) =>{ sendForm(e)}}>
                                <MaterialInput type="text" label="Логин" error={errorLogin} handleChange={handleLogin}/>
                                <MaterialInput type="password" label="Пароль" error={errorPassword} handleChange={handlePassword}/>
                                { errorCredentials ? <p className="xs text-danger error-message">Не верный логин или пароль</p> : null}
                                <button type="submit" className="btn btn-primary btn-block">Войти</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}

export default Login
